//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.
{
    using System;
    
    
    public class APPLICATION : System.ComponentModel.INotifyPropertyChanged
    {
        
        // 
        public string application_idValue;
        
        // 
        public string active_indValue;
        
        // 
        public string application_typeValue;
        
        // 
        public string contract_idValue;
        
        // 
        public string current_statusValue;
        
        // 
        public string decisionValue;
        
        // 
        public System.DateTime decision_dateValue;
        
        // 
        public System.DateTime effective_dateValue;
        
        // 
        public System.DateTime expiry_dateValue;
        
        // 
        public string extension_idValue;
        
        // 
        public string fees_descValue;
        
        // 
        public string fees_paid_indValue;
        
        // 
        public string ppdm_guidValue;
        
        // 
        public string previous_application_idValue;
        
        // 
        public string rate_schedule_idValue;
        
        // 
        public System.DateTime received_dateValue;
        
        // 
        public string reference_numValue;
        
        // 
        public string remarkValue;
        
        // 
        public string resubmission_indValue;
        
        // 
        public string section_of_actValue;
        
        // 
        public System.DateTime section_of_act_dateValue;
        
        // 
        public string sourceValue;
        
        // 
        public string submission_complete_indValue;
        
        // 
        public string submission_descValue;
        
        // 
        public string submitted_byValue;
        
        // 
        public System.DateTime submitted_dateValue;
        
        // 
        public string submitted_toValue;
        
        // 
        public string row_changed_byValue;
        
        // 
        public System.DateTime row_changed_dateValue;
        
        // 
        public string row_created_byValue;
        
        // 
        public System.DateTime row_created_dateValue;
        
        // 
        public string row_qualityValue;
        
        // 
        public string ClassNameValue;
        
        public APPLICATION()
        {
        }
        
        // 
        public string application_id
        {
            get
            {
                return this.application_idValue;
                return base.application_id;
            }
            set
            {
                this.application_idValue = value;
            }
        }
        
        // 
        public string active_ind
        {
            get
            {
                return this.active_indValue;
                return base.active_ind;
            }
            set
            {
                this.active_indValue = value;
            }
        }
        
        // 
        public string application_type
        {
            get
            {
                return this.application_typeValue;
                return base.application_type;
            }
            set
            {
                this.application_typeValue = value;
            }
        }
        
        // 
        public string contract_id
        {
            get
            {
                return this.contract_idValue;
                return base.contract_id;
            }
            set
            {
                this.contract_idValue = value;
            }
        }
        
        // 
        public string current_status
        {
            get
            {
                return this.current_statusValue;
                return base.current_status;
            }
            set
            {
                this.current_statusValue = value;
            }
        }
        
        // 
        public string decision
        {
            get
            {
                return this.decisionValue;
                return base.decision;
            }
            set
            {
                this.decisionValue = value;
            }
        }
        
        // 
        public System.DateTime decision_date
        {
            get
            {
                return this.decision_dateValue;
                return base.decision_date;
            }
            set
            {
                this.decision_dateValue = value;
            }
        }
        
        // 
        public System.DateTime effective_date
        {
            get
            {
                return this.effective_dateValue;
                return base.effective_date;
            }
            set
            {
                this.effective_dateValue = value;
            }
        }
        
        // 
        public System.DateTime expiry_date
        {
            get
            {
                return this.expiry_dateValue;
                return base.expiry_date;
            }
            set
            {
                this.expiry_dateValue = value;
            }
        }
        
        // 
        public string extension_id
        {
            get
            {
                return this.extension_idValue;
                return base.extension_id;
            }
            set
            {
                this.extension_idValue = value;
            }
        }
        
        // 
        public string fees_desc
        {
            get
            {
                return this.fees_descValue;
                return base.fees_desc;
            }
            set
            {
                this.fees_descValue = value;
            }
        }
        
        // 
        public string fees_paid_ind
        {
            get
            {
                return this.fees_paid_indValue;
                return base.fees_paid_ind;
            }
            set
            {
                this.fees_paid_indValue = value;
            }
        }
        
        // 
        public string ppdm_guid
        {
            get
            {
                return this.ppdm_guidValue;
                return base.ppdm_guid;
            }
            set
            {
                this.ppdm_guidValue = value;
            }
        }
        
        // 
        public string previous_application_id
        {
            get
            {
                return this.previous_application_idValue;
                return base.previous_application_id;
            }
            set
            {
                this.previous_application_idValue = value;
            }
        }
        
        // 
        public string rate_schedule_id
        {
            get
            {
                return this.rate_schedule_idValue;
                return base.rate_schedule_id;
            }
            set
            {
                this.rate_schedule_idValue = value;
            }
        }
        
        // 
        public System.DateTime received_date
        {
            get
            {
                return this.received_dateValue;
                return base.received_date;
            }
            set
            {
                this.received_dateValue = value;
            }
        }
        
        // 
        public string reference_num
        {
            get
            {
                return this.reference_numValue;
                return base.reference_num;
            }
            set
            {
                this.reference_numValue = value;
            }
        }
        
        // 
        public string remark
        {
            get
            {
                return this.remarkValue;
                return base.remark;
            }
            set
            {
                this.remarkValue = value;
            }
        }
        
        // 
        public string resubmission_ind
        {
            get
            {
                return this.resubmission_indValue;
                return base.resubmission_ind;
            }
            set
            {
                this.resubmission_indValue = value;
            }
        }
        
        // 
        public string section_of_act
        {
            get
            {
                return this.section_of_actValue;
                return base.section_of_act;
            }
            set
            {
                this.section_of_actValue = value;
            }
        }
        
        // 
        public System.DateTime section_of_act_date
        {
            get
            {
                return this.section_of_act_dateValue;
                return base.section_of_act_date;
            }
            set
            {
                this.section_of_act_dateValue = value;
            }
        }
        
        // 
        public string source
        {
            get
            {
                return this.sourceValue;
                return base.source;
            }
            set
            {
                this.sourceValue = value;
            }
        }
        
        // 
        public string submission_complete_ind
        {
            get
            {
                return this.submission_complete_indValue;
                return base.submission_complete_ind;
            }
            set
            {
                this.submission_complete_indValue = value;
            }
        }
        
        // 
        public string submission_desc
        {
            get
            {
                return this.submission_descValue;
                return base.submission_desc;
            }
            set
            {
                this.submission_descValue = value;
            }
        }
        
        // 
        public string submitted_by
        {
            get
            {
                return this.submitted_byValue;
                return base.submitted_by;
            }
            set
            {
                this.submitted_byValue = value;
            }
        }
        
        // 
        public System.DateTime submitted_date
        {
            get
            {
                return this.submitted_dateValue;
                return base.submitted_date;
            }
            set
            {
                this.submitted_dateValue = value;
            }
        }
        
        // 
        public string submitted_to
        {
            get
            {
                return this.submitted_toValue;
                return base.submitted_to;
            }
            set
            {
                this.submitted_toValue = value;
            }
        }
        
        // 
        public string row_changed_by
        {
            get
            {
                return this.row_changed_byValue;
                return base.row_changed_by;
            }
            set
            {
                this.row_changed_byValue = value;
            }
        }
        
        // 
        public System.DateTime row_changed_date
        {
            get
            {
                return this.row_changed_dateValue;
                return base.row_changed_date;
            }
            set
            {
                this.row_changed_dateValue = value;
            }
        }
        
        // 
        public string row_created_by
        {
            get
            {
                return this.row_created_byValue;
                return base.row_created_by;
            }
            set
            {
                this.row_created_byValue = value;
            }
        }
        
        // 
        public System.DateTime row_created_date
        {
            get
            {
                return this.row_created_dateValue;
                return base.row_created_date;
            }
            set
            {
                this.row_created_dateValue = value;
            }
        }
        
        // 
        public string row_quality
        {
            get
            {
                return this.row_qualityValue;
                return base.row_quality;
            }
            set
            {
                this.row_qualityValue = value;
            }
        }
        
        // 
        public string ClassName
        {
            get
            {
                return this.ClassNameValue;
                return base.ClassName;
            }
            set
            {
                this.ClassNameValue = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler;
            handler = this.PropertyChanged;
            if ((null != handler))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
