//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea
{
    using System;
    
    
    public class APPLICATION_COMPONENT : System.ComponentModel.INotifyPropertyChanged
    {
        
        private static System.Collections.Generic.Dictionary<string, System.ComponentModel.PropertyChangedEventArgs> propertyChangedEventArgs = new System.Collections.Generic.Dictionary<string, System.ComponentModel.PropertyChangedEventArgs>();
        
        // 
        public string application_idValue;
        
        // 
        public int component_obs_noValue;
        
        // 
        public string active_indValue;
        
        // 
        public int activity_obs_noValue;
        
        // 
        public string analysis_idValue;
        
        // 
        public string application_component_typeValue;
        
        // 
        public string area_idValue;
        
        // 
        public string area_typeValue;
        
        // 
        public string authority_idValue;
        
        // 
        public string ba_organization_idValue;
        
        // 
        public decimal ba_organization_seq_noValue;
        
        // 
        public string business_associateValue;
        
        // 
        public string catalogue_additive_idValue;
        
        // 
        public string catalogue_equip_idValue;
        
        // 
        public string classification_system_idValue;
        
        // 
        public string class_level_idValue;
        
        // 
        public string consent_idValue;
        
        // 
        public string consult_idValue;
        
        // 
        public string contest_idValue;
        
        // 
        public string contract_idValue;
        
        // 
        public string ecozone_idValue;
        
        // 
        public System.DateTime effective_dateValue;
        
        // 
        public string employee_ba_idValue;
        
        // 
        public int employee_obs_noValue;
        
        // 
        public string employer_ba_idValue;
        
        // 
        public string entitlement_idValue;
        
        // 
        public string equipment_idValue;
        
        // 
        public System.DateTime expiry_dateValue;
        
        // 
        public string facility_idValue;
        
        // 
        public string facility_typeValue;
        
        // 
        public string field_idValue;
        
        // 
        public string finance_idValue;
        
        // 
        public string fossil_idValue;
        
        // 
        public string incident_idValue;
        
        // 
        public string incident_set_idValue;
        
        // 
        public string incident_typeValue;
        
        // 
        public string information_item_idValue;
        
        // 
        public string info_item_typeValue;
        
        // 
        public string instrument_idValue;
        
        // 
        public string interest_set_idValue;
        
        // 
        public decimal interest_set_seq_noValue;
        
        // 
        public string jurisdictionValue;
        
        // 
        public string land_right_idValue;
        
        // 
        public string land_right_typeValue;
        
        // 
        public string land_sale_numberValue;
        
        // 
        public string languageValue;
        
        // 
        public string lithology_log_idValue;
        
        // 
        public string lith_log_sourceValue;
        
        // 
        public string notification_idValue;
        
        // 
        public string obligation_idValue;
        
        // 
        public decimal obligation_seq_noValue;
        
        // 
        public string paleo_summary_idValue;
        
        // 
        public string pden_idValue;
        
        // 
        public string pden_sourceValue;
        
        // 
        public string pden_typeValue;
        
        // 
        public string physical_item_idValue;
        
        // 
        public string pool_idValue;
        
        // 
        public string ppdm_guidValue;
        
        // 
        public string ppdm_system_idValue;
        
        // 
        public string ppdm_table_nameValue;
        
        // 
        public string product_typeValue;
        
        // 
        public string project_idValue;
        
        // 
        public string pr_str_sourceValue;
        
        // 
        public string pr_str_uwiValue;
        
        // 
        public string rate_schedule_idValue;
        
        // 
        public string referenced_guidValue;
        
        // 
        public string referenced_system_idValue;
        
        // 
        public string referenced_table_nameValue;
        
        // 
        public string remarkValue;
        
        // 
        public string resent_idValue;
        
        // 
        public string sample_anal_sourceValue;
        
        // 
        public string seis_set_idValue;
        
        // 
        public string seis_set_typeValue;
        
        // 
        public string sf_typeValue;
        
        // 
        public string sourceValue;
        
        // 
        public string spatial_description_idValue;
        
        // 
        public int spatial_obs_noValue;
        
        // 
        public string store_idValue;
        
        // 
        public int store_structure_obs_noValue;
        
        // 
        public string strat_name_set_idValue;
        
        // 
        public string strat_unit_idValue;
        
        // 
        public string string_idValue;
        
        // 
        public string support_facility_idValue;
        
        // 
        public string thesaurus_idValue;
        
        // 
        public string thesaurus_word_idValue;
        
        // 
        public string uwiValue;
        
        // 
        public string well_activity_set_idValue;
        
        // 
        public string well_activity_sourceValue;
        
        // 
        public string well_activity_typeValue;
        
        // 
        public string well_activity_uwiValue;
        
        // 
        public string work_order_idValue;
        
        // 
        public string row_changed_byValue;
        
        // 
        public System.DateTime row_changed_dateValue;
        
        // 
        public string row_created_byValue;
        
        // 
        public System.DateTime row_created_dateValue;
        
        // 
        public string row_qualityValue;
        
        // 
        public string ClassNameValue;
        
        public APPLICATION_COMPONENT()
        {
        }
        
        protected static System.Collections.Generic.Dictionary<string, System.ComponentModel.PropertyChangedEventArgs> PropertyChangedEventArgs
        {
            get
            {
                return APPLICATION_COMPONENT.propertyChangedEventArgs;
            }
        }
        
        // 
        public string application_id
        {
            get
            {
                return this.application_idValue;
            }
            set
            {
                this.application_idValue = value;
                this.OnPropertyChanged("application_id");
            }
        }
        
        // 
        public int component_obs_no
        {
            get
            {
                return this.component_obs_noValue;
            }
            set
            {
                this.component_obs_noValue = value;
                this.OnPropertyChanged("component_obs_no");
            }
        }
        
        // 
        public string active_ind
        {
            get
            {
                return this.active_indValue;
            }
            set
            {
                this.active_indValue = value;
                this.OnPropertyChanged("active_ind");
            }
        }
        
        // 
        public int activity_obs_no
        {
            get
            {
                return this.activity_obs_noValue;
            }
            set
            {
                this.activity_obs_noValue = value;
                this.OnPropertyChanged("activity_obs_no");
            }
        }
        
        // 
        public string analysis_id
        {
            get
            {
                return this.analysis_idValue;
            }
            set
            {
                this.analysis_idValue = value;
                this.OnPropertyChanged("analysis_id");
            }
        }
        
        // 
        public string application_component_type
        {
            get
            {
                return this.application_component_typeValue;
            }
            set
            {
                this.application_component_typeValue = value;
                this.OnPropertyChanged("application_component_type");
            }
        }
        
        // 
        public string area_id
        {
            get
            {
                return this.area_idValue;
            }
            set
            {
                this.area_idValue = value;
                this.OnPropertyChanged("area_id");
            }
        }
        
        // 
        public string area_type
        {
            get
            {
                return this.area_typeValue;
            }
            set
            {
                this.area_typeValue = value;
                this.OnPropertyChanged("area_type");
            }
        }
        
        // 
        public string authority_id
        {
            get
            {
                return this.authority_idValue;
            }
            set
            {
                this.authority_idValue = value;
                this.OnPropertyChanged("authority_id");
            }
        }
        
        // 
        public string ba_organization_id
        {
            get
            {
                return this.ba_organization_idValue;
            }
            set
            {
                this.ba_organization_idValue = value;
                this.OnPropertyChanged("ba_organization_id");
            }
        }
        
        // 
        public decimal ba_organization_seq_no
        {
            get
            {
                return this.ba_organization_seq_noValue;
            }
            set
            {
                this.ba_organization_seq_noValue = value;
                this.OnPropertyChanged("ba_organization_seq_no");
            }
        }
        
        // 
        public string business_associate
        {
            get
            {
                return this.business_associateValue;
            }
            set
            {
                this.business_associateValue = value;
                this.OnPropertyChanged("business_associate");
            }
        }
        
        // 
        public string catalogue_additive_id
        {
            get
            {
                return this.catalogue_additive_idValue;
            }
            set
            {
                this.catalogue_additive_idValue = value;
                this.OnPropertyChanged("catalogue_additive_id");
            }
        }
        
        // 
        public string catalogue_equip_id
        {
            get
            {
                return this.catalogue_equip_idValue;
            }
            set
            {
                this.catalogue_equip_idValue = value;
                this.OnPropertyChanged("catalogue_equip_id");
            }
        }
        
        // 
        public string classification_system_id
        {
            get
            {
                return this.classification_system_idValue;
            }
            set
            {
                this.classification_system_idValue = value;
                this.OnPropertyChanged("classification_system_id");
            }
        }
        
        // 
        public string class_level_id
        {
            get
            {
                return this.class_level_idValue;
            }
            set
            {
                this.class_level_idValue = value;
                this.OnPropertyChanged("class_level_id");
            }
        }
        
        // 
        public string consent_id
        {
            get
            {
                return this.consent_idValue;
            }
            set
            {
                this.consent_idValue = value;
                this.OnPropertyChanged("consent_id");
            }
        }
        
        // 
        public string consult_id
        {
            get
            {
                return this.consult_idValue;
            }
            set
            {
                this.consult_idValue = value;
                this.OnPropertyChanged("consult_id");
            }
        }
        
        // 
        public string contest_id
        {
            get
            {
                return this.contest_idValue;
            }
            set
            {
                this.contest_idValue = value;
                this.OnPropertyChanged("contest_id");
            }
        }
        
        // 
        public string contract_id
        {
            get
            {
                return this.contract_idValue;
            }
            set
            {
                this.contract_idValue = value;
                this.OnPropertyChanged("contract_id");
            }
        }
        
        // 
        public string ecozone_id
        {
            get
            {
                return this.ecozone_idValue;
            }
            set
            {
                this.ecozone_idValue = value;
                this.OnPropertyChanged("ecozone_id");
            }
        }
        
        // 
        public System.DateTime effective_date
        {
            get
            {
                return this.effective_dateValue;
            }
            set
            {
                this.effective_dateValue = value;
                this.OnPropertyChanged("effective_date");
            }
        }
        
        // 
        public string employee_ba_id
        {
            get
            {
                return this.employee_ba_idValue;
            }
            set
            {
                this.employee_ba_idValue = value;
                this.OnPropertyChanged("employee_ba_id");
            }
        }
        
        // 
        public int employee_obs_no
        {
            get
            {
                return this.employee_obs_noValue;
            }
            set
            {
                this.employee_obs_noValue = value;
                this.OnPropertyChanged("employee_obs_no");
            }
        }
        
        // 
        public string employer_ba_id
        {
            get
            {
                return this.employer_ba_idValue;
            }
            set
            {
                this.employer_ba_idValue = value;
                this.OnPropertyChanged("employer_ba_id");
            }
        }
        
        // 
        public string entitlement_id
        {
            get
            {
                return this.entitlement_idValue;
            }
            set
            {
                this.entitlement_idValue = value;
                this.OnPropertyChanged("entitlement_id");
            }
        }
        
        // 
        public string equipment_id
        {
            get
            {
                return this.equipment_idValue;
            }
            set
            {
                this.equipment_idValue = value;
                this.OnPropertyChanged("equipment_id");
            }
        }
        
        // 
        public System.DateTime expiry_date
        {
            get
            {
                return this.expiry_dateValue;
            }
            set
            {
                this.expiry_dateValue = value;
                this.OnPropertyChanged("expiry_date");
            }
        }
        
        // 
        public string facility_id
        {
            get
            {
                return this.facility_idValue;
            }
            set
            {
                this.facility_idValue = value;
                this.OnPropertyChanged("facility_id");
            }
        }
        
        // 
        public string facility_type
        {
            get
            {
                return this.facility_typeValue;
            }
            set
            {
                this.facility_typeValue = value;
                this.OnPropertyChanged("facility_type");
            }
        }
        
        // 
        public string field_id
        {
            get
            {
                return this.field_idValue;
            }
            set
            {
                this.field_idValue = value;
                this.OnPropertyChanged("field_id");
            }
        }
        
        // 
        public string finance_id
        {
            get
            {
                return this.finance_idValue;
            }
            set
            {
                this.finance_idValue = value;
                this.OnPropertyChanged("finance_id");
            }
        }
        
        // 
        public string fossil_id
        {
            get
            {
                return this.fossil_idValue;
            }
            set
            {
                this.fossil_idValue = value;
                this.OnPropertyChanged("fossil_id");
            }
        }
        
        // 
        public string incident_id
        {
            get
            {
                return this.incident_idValue;
            }
            set
            {
                this.incident_idValue = value;
                this.OnPropertyChanged("incident_id");
            }
        }
        
        // 
        public string incident_set_id
        {
            get
            {
                return this.incident_set_idValue;
            }
            set
            {
                this.incident_set_idValue = value;
                this.OnPropertyChanged("incident_set_id");
            }
        }
        
        // 
        public string incident_type
        {
            get
            {
                return this.incident_typeValue;
            }
            set
            {
                this.incident_typeValue = value;
                this.OnPropertyChanged("incident_type");
            }
        }
        
        // 
        public string information_item_id
        {
            get
            {
                return this.information_item_idValue;
            }
            set
            {
                this.information_item_idValue = value;
                this.OnPropertyChanged("information_item_id");
            }
        }
        
        // 
        public string info_item_type
        {
            get
            {
                return this.info_item_typeValue;
            }
            set
            {
                this.info_item_typeValue = value;
                this.OnPropertyChanged("info_item_type");
            }
        }
        
        // 
        public string instrument_id
        {
            get
            {
                return this.instrument_idValue;
            }
            set
            {
                this.instrument_idValue = value;
                this.OnPropertyChanged("instrument_id");
            }
        }
        
        // 
        public string interest_set_id
        {
            get
            {
                return this.interest_set_idValue;
            }
            set
            {
                this.interest_set_idValue = value;
                this.OnPropertyChanged("interest_set_id");
            }
        }
        
        // 
        public decimal interest_set_seq_no
        {
            get
            {
                return this.interest_set_seq_noValue;
            }
            set
            {
                this.interest_set_seq_noValue = value;
                this.OnPropertyChanged("interest_set_seq_no");
            }
        }
        
        // 
        public string jurisdiction
        {
            get
            {
                return this.jurisdictionValue;
            }
            set
            {
                this.jurisdictionValue = value;
                this.OnPropertyChanged("jurisdiction");
            }
        }
        
        // 
        public string land_right_id
        {
            get
            {
                return this.land_right_idValue;
            }
            set
            {
                this.land_right_idValue = value;
                this.OnPropertyChanged("land_right_id");
            }
        }
        
        // 
        public string land_right_type
        {
            get
            {
                return this.land_right_typeValue;
            }
            set
            {
                this.land_right_typeValue = value;
                this.OnPropertyChanged("land_right_type");
            }
        }
        
        // 
        public string land_sale_number
        {
            get
            {
                return this.land_sale_numberValue;
            }
            set
            {
                this.land_sale_numberValue = value;
                this.OnPropertyChanged("land_sale_number");
            }
        }
        
        // 
        public string language
        {
            get
            {
                return this.languageValue;
            }
            set
            {
                this.languageValue = value;
                this.OnPropertyChanged("language");
            }
        }
        
        // 
        public string lithology_log_id
        {
            get
            {
                return this.lithology_log_idValue;
            }
            set
            {
                this.lithology_log_idValue = value;
                this.OnPropertyChanged("lithology_log_id");
            }
        }
        
        // 
        public string lith_log_source
        {
            get
            {
                return this.lith_log_sourceValue;
            }
            set
            {
                this.lith_log_sourceValue = value;
                this.OnPropertyChanged("lith_log_source");
            }
        }
        
        // 
        public string notification_id
        {
            get
            {
                return this.notification_idValue;
            }
            set
            {
                this.notification_idValue = value;
                this.OnPropertyChanged("notification_id");
            }
        }
        
        // 
        public string obligation_id
        {
            get
            {
                return this.obligation_idValue;
            }
            set
            {
                this.obligation_idValue = value;
                this.OnPropertyChanged("obligation_id");
            }
        }
        
        // 
        public decimal obligation_seq_no
        {
            get
            {
                return this.obligation_seq_noValue;
            }
            set
            {
                this.obligation_seq_noValue = value;
                this.OnPropertyChanged("obligation_seq_no");
            }
        }
        
        // 
        public string paleo_summary_id
        {
            get
            {
                return this.paleo_summary_idValue;
            }
            set
            {
                this.paleo_summary_idValue = value;
                this.OnPropertyChanged("paleo_summary_id");
            }
        }
        
        // 
        public string pden_id
        {
            get
            {
                return this.pden_idValue;
            }
            set
            {
                this.pden_idValue = value;
                this.OnPropertyChanged("pden_id");
            }
        }
        
        // 
        public string pden_source
        {
            get
            {
                return this.pden_sourceValue;
            }
            set
            {
                this.pden_sourceValue = value;
                this.OnPropertyChanged("pden_source");
            }
        }
        
        // 
        public string pden_type
        {
            get
            {
                return this.pden_typeValue;
            }
            set
            {
                this.pden_typeValue = value;
                this.OnPropertyChanged("pden_type");
            }
        }
        
        // 
        public string physical_item_id
        {
            get
            {
                return this.physical_item_idValue;
            }
            set
            {
                this.physical_item_idValue = value;
                this.OnPropertyChanged("physical_item_id");
            }
        }
        
        // 
        public string pool_id
        {
            get
            {
                return this.pool_idValue;
            }
            set
            {
                this.pool_idValue = value;
                this.OnPropertyChanged("pool_id");
            }
        }
        
        // 
        public string ppdm_guid
        {
            get
            {
                return this.ppdm_guidValue;
            }
            set
            {
                this.ppdm_guidValue = value;
                this.OnPropertyChanged("ppdm_guid");
            }
        }
        
        // 
        public string ppdm_system_id
        {
            get
            {
                return this.ppdm_system_idValue;
            }
            set
            {
                this.ppdm_system_idValue = value;
                this.OnPropertyChanged("ppdm_system_id");
            }
        }
        
        // 
        public string ppdm_table_name
        {
            get
            {
                return this.ppdm_table_nameValue;
            }
            set
            {
                this.ppdm_table_nameValue = value;
                this.OnPropertyChanged("ppdm_table_name");
            }
        }
        
        // 
        public string product_type
        {
            get
            {
                return this.product_typeValue;
            }
            set
            {
                this.product_typeValue = value;
                this.OnPropertyChanged("product_type");
            }
        }
        
        // 
        public string project_id
        {
            get
            {
                return this.project_idValue;
            }
            set
            {
                this.project_idValue = value;
                this.OnPropertyChanged("project_id");
            }
        }
        
        // 
        public string pr_str_source
        {
            get
            {
                return this.pr_str_sourceValue;
            }
            set
            {
                this.pr_str_sourceValue = value;
                this.OnPropertyChanged("pr_str_source");
            }
        }
        
        // 
        public string pr_str_uwi
        {
            get
            {
                return this.pr_str_uwiValue;
            }
            set
            {
                this.pr_str_uwiValue = value;
                this.OnPropertyChanged("pr_str_uwi");
            }
        }
        
        // 
        public string rate_schedule_id
        {
            get
            {
                return this.rate_schedule_idValue;
            }
            set
            {
                this.rate_schedule_idValue = value;
                this.OnPropertyChanged("rate_schedule_id");
            }
        }
        
        // 
        public string referenced_guid
        {
            get
            {
                return this.referenced_guidValue;
            }
            set
            {
                this.referenced_guidValue = value;
                this.OnPropertyChanged("referenced_guid");
            }
        }
        
        // 
        public string referenced_system_id
        {
            get
            {
                return this.referenced_system_idValue;
            }
            set
            {
                this.referenced_system_idValue = value;
                this.OnPropertyChanged("referenced_system_id");
            }
        }
        
        // 
        public string referenced_table_name
        {
            get
            {
                return this.referenced_table_nameValue;
            }
            set
            {
                this.referenced_table_nameValue = value;
                this.OnPropertyChanged("referenced_table_name");
            }
        }
        
        // 
        public string remark
        {
            get
            {
                return this.remarkValue;
            }
            set
            {
                this.remarkValue = value;
                this.OnPropertyChanged("remark");
            }
        }
        
        // 
        public string resent_id
        {
            get
            {
                return this.resent_idValue;
            }
            set
            {
                this.resent_idValue = value;
                this.OnPropertyChanged("resent_id");
            }
        }
        
        // 
        public string sample_anal_source
        {
            get
            {
                return this.sample_anal_sourceValue;
            }
            set
            {
                this.sample_anal_sourceValue = value;
                this.OnPropertyChanged("sample_anal_source");
            }
        }
        
        // 
        public string seis_set_id
        {
            get
            {
                return this.seis_set_idValue;
            }
            set
            {
                this.seis_set_idValue = value;
                this.OnPropertyChanged("seis_set_id");
            }
        }
        
        // 
        public string seis_set_type
        {
            get
            {
                return this.seis_set_typeValue;
            }
            set
            {
                this.seis_set_typeValue = value;
                this.OnPropertyChanged("seis_set_type");
            }
        }
        
        // 
        public string sf_type
        {
            get
            {
                return this.sf_typeValue;
            }
            set
            {
                this.sf_typeValue = value;
                this.OnPropertyChanged("sf_type");
            }
        }
        
        // 
        public string source
        {
            get
            {
                return this.sourceValue;
            }
            set
            {
                this.sourceValue = value;
                this.OnPropertyChanged("source");
            }
        }
        
        // 
        public string spatial_description_id
        {
            get
            {
                return this.spatial_description_idValue;
            }
            set
            {
                this.spatial_description_idValue = value;
                this.OnPropertyChanged("spatial_description_id");
            }
        }
        
        // 
        public int spatial_obs_no
        {
            get
            {
                return this.spatial_obs_noValue;
            }
            set
            {
                this.spatial_obs_noValue = value;
                this.OnPropertyChanged("spatial_obs_no");
            }
        }
        
        // 
        public string store_id
        {
            get
            {
                return this.store_idValue;
            }
            set
            {
                this.store_idValue = value;
                this.OnPropertyChanged("store_id");
            }
        }
        
        // 
        public int store_structure_obs_no
        {
            get
            {
                return this.store_structure_obs_noValue;
            }
            set
            {
                this.store_structure_obs_noValue = value;
                this.OnPropertyChanged("store_structure_obs_no");
            }
        }
        
        // 
        public string strat_name_set_id
        {
            get
            {
                return this.strat_name_set_idValue;
            }
            set
            {
                this.strat_name_set_idValue = value;
                this.OnPropertyChanged("strat_name_set_id");
            }
        }
        
        // 
        public string strat_unit_id
        {
            get
            {
                return this.strat_unit_idValue;
            }
            set
            {
                this.strat_unit_idValue = value;
                this.OnPropertyChanged("strat_unit_id");
            }
        }
        
        // 
        public string string_id
        {
            get
            {
                return this.string_idValue;
            }
            set
            {
                this.string_idValue = value;
                this.OnPropertyChanged("string_id");
            }
        }
        
        // 
        public string support_facility_id
        {
            get
            {
                return this.support_facility_idValue;
            }
            set
            {
                this.support_facility_idValue = value;
                this.OnPropertyChanged("support_facility_id");
            }
        }
        
        // 
        public string thesaurus_id
        {
            get
            {
                return this.thesaurus_idValue;
            }
            set
            {
                this.thesaurus_idValue = value;
                this.OnPropertyChanged("thesaurus_id");
            }
        }
        
        // 
        public string thesaurus_word_id
        {
            get
            {
                return this.thesaurus_word_idValue;
            }
            set
            {
                this.thesaurus_word_idValue = value;
                this.OnPropertyChanged("thesaurus_word_id");
            }
        }
        
        // 
        public string uwi
        {
            get
            {
                return this.uwiValue;
            }
            set
            {
                this.uwiValue = value;
                this.OnPropertyChanged("uwi");
            }
        }
        
        // 
        public string well_activity_set_id
        {
            get
            {
                return this.well_activity_set_idValue;
            }
            set
            {
                this.well_activity_set_idValue = value;
                this.OnPropertyChanged("well_activity_set_id");
            }
        }
        
        // 
        public string well_activity_source
        {
            get
            {
                return this.well_activity_sourceValue;
            }
            set
            {
                this.well_activity_sourceValue = value;
                this.OnPropertyChanged("well_activity_source");
            }
        }
        
        // 
        public string well_activity_type
        {
            get
            {
                return this.well_activity_typeValue;
            }
            set
            {
                this.well_activity_typeValue = value;
                this.OnPropertyChanged("well_activity_type");
            }
        }
        
        // 
        public string well_activity_uwi
        {
            get
            {
                return this.well_activity_uwiValue;
            }
            set
            {
                this.well_activity_uwiValue = value;
                this.OnPropertyChanged("well_activity_uwi");
            }
        }
        
        // 
        public string work_order_id
        {
            get
            {
                return this.work_order_idValue;
            }
            set
            {
                this.work_order_idValue = value;
                this.OnPropertyChanged("work_order_id");
            }
        }
        
        // 
        public string row_changed_by
        {
            get
            {
                return this.row_changed_byValue;
            }
            set
            {
                this.row_changed_byValue = value;
                this.OnPropertyChanged("row_changed_by");
            }
        }
        
        // 
        public System.DateTime row_changed_date
        {
            get
            {
                return this.row_changed_dateValue;
            }
            set
            {
                this.row_changed_dateValue = value;
                this.OnPropertyChanged("row_changed_date");
            }
        }
        
        // 
        public string row_created_by
        {
            get
            {
                return this.row_created_byValue;
            }
            set
            {
                this.row_created_byValue = value;
                this.OnPropertyChanged("row_created_by");
            }
        }
        
        // 
        public System.DateTime row_created_date
        {
            get
            {
                return this.row_created_dateValue;
            }
            set
            {
                this.row_created_dateValue = value;
                this.OnPropertyChanged("row_created_date");
            }
        }
        
        // 
        public string row_quality
        {
            get
            {
                return this.row_qualityValue;
            }
            set
            {
                this.row_qualityValue = value;
                this.OnPropertyChanged("row_quality");
            }
        }
        
        // 
        public string ClassName
        {
            get
            {
                return this.ClassNameValue;
            }
            set
            {
                this.ClassNameValue = value;
                this.OnPropertyChanged("ClassName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged == null))
            {
                return;
            }
            System.ComponentModel.PropertyChangedEventArgs eventArgs;
            if ((APPLICATION_COMPONENT.PropertyChangedEventArgs.TryGetValue(propertyName, out eventArgs) == false))
            {
                eventArgs = new System.ComponentModel.PropertyChangedEventArgs(propertyName);
                APPLICATION_COMPONENT.PropertyChangedEventArgs.Add(propertyName, eventArgs);
            }
            this.PropertyChanged(this, eventArgs);
        }
        
        protected virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler;
            handler = this.PropertyChanged;
            if ((null != handler))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
