//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea
{
    using System;
    
    
    public class AREA : System.ComponentModel.INotifyPropertyChanged
    {
        
        // 
        private string area_idValue;
        
        // 
        private string area_typeValue;
        
        // 
        private string active_indValue;
        
        // 
        private decimal area_max_latitudeValue;
        
        // 
        private decimal area_max_longitudeValue;
        
        // 
        private decimal area_min_latitudeValue;
        
        // 
        private decimal area_min_longitudeValue;
        
        // 
        private decimal area_numeric_idValue;
        
        // 
        private string coord_acquisition_idValue;
        
        // 
        private string coord_system_idValue;
        
        // 
        private System.DateTime effective_dateValue;
        
        // 
        private System.DateTime expiry_dateValue;
        
        // 
        private string local_coord_system_idValue;
        
        // 
        private string ppdm_guidValue;
        
        // 
        private string preferred_nameValue;
        
        // 
        private string remarkValue;
        
        // 
        private string sourceValue;
        
        // 
        private string source_documentValue;
        
        // 
        private string row_changed_byValue;
        
        // 
        private System.DateTime row_changed_dateValue;
        
        // 
        private string row_created_byValue;
        
        // 
        private System.DateTime row_created_dateValue;
        
        // 
        private string row_qualityValue;
        
        // 
        private string ClassNameValue;
        
        public AREA()
        {
        }
        
        // 
        public string area_id
        {
            get
            {
                return this.area_idValue;
            }
            set
            {
                this.area_idValue = value;
                this.OnPropertyChanged("area_id");
            }
        }
        
        // 
        public string area_type
        {
            get
            {
                return this.area_typeValue;
            }
            set
            {
                this.area_typeValue = value;
                this.OnPropertyChanged("area_type");
            }
        }
        
        // 
        public string active_ind
        {
            get
            {
                return this.active_indValue;
            }
            set
            {
                this.active_indValue = value;
                this.OnPropertyChanged("active_ind");
            }
        }
        
        // 
        public decimal area_max_latitude
        {
            get
            {
                return this.area_max_latitudeValue;
            }
            set
            {
                this.area_max_latitudeValue = value;
                this.OnPropertyChanged("area_max_latitude");
            }
        }
        
        // 
        public decimal area_max_longitude
        {
            get
            {
                return this.area_max_longitudeValue;
            }
            set
            {
                this.area_max_longitudeValue = value;
                this.OnPropertyChanged("area_max_longitude");
            }
        }
        
        // 
        public decimal area_min_latitude
        {
            get
            {
                return this.area_min_latitudeValue;
            }
            set
            {
                this.area_min_latitudeValue = value;
                this.OnPropertyChanged("area_min_latitude");
            }
        }
        
        // 
        public decimal area_min_longitude
        {
            get
            {
                return this.area_min_longitudeValue;
            }
            set
            {
                this.area_min_longitudeValue = value;
                this.OnPropertyChanged("area_min_longitude");
            }
        }
        
        // 
        public decimal area_numeric_id
        {
            get
            {
                return this.area_numeric_idValue;
            }
            set
            {
                this.area_numeric_idValue = value;
                this.OnPropertyChanged("area_numeric_id");
            }
        }
        
        // 
        public string coord_acquisition_id
        {
            get
            {
                return this.coord_acquisition_idValue;
            }
            set
            {
                this.coord_acquisition_idValue = value;
                this.OnPropertyChanged("coord_acquisition_id");
            }
        }
        
        // 
        public string coord_system_id
        {
            get
            {
                return this.coord_system_idValue;
            }
            set
            {
                this.coord_system_idValue = value;
                this.OnPropertyChanged("coord_system_id");
            }
        }
        
        // 
        public System.DateTime effective_date
        {
            get
            {
                return this.effective_dateValue;
            }
            set
            {
                this.effective_dateValue = value;
                this.OnPropertyChanged("effective_date");
            }
        }
        
        // 
        public System.DateTime expiry_date
        {
            get
            {
                return this.expiry_dateValue;
            }
            set
            {
                this.expiry_dateValue = value;
                this.OnPropertyChanged("expiry_date");
            }
        }
        
        // 
        public string local_coord_system_id
        {
            get
            {
                return this.local_coord_system_idValue;
            }
            set
            {
                this.local_coord_system_idValue = value;
                this.OnPropertyChanged("local_coord_system_id");
            }
        }
        
        // 
        public string ppdm_guid
        {
            get
            {
                return this.ppdm_guidValue;
            }
            set
            {
                this.ppdm_guidValue = value;
                this.OnPropertyChanged("ppdm_guid");
            }
        }
        
        // 
        public string preferred_name
        {
            get
            {
                return this.preferred_nameValue;
            }
            set
            {
                this.preferred_nameValue = value;
                this.OnPropertyChanged("preferred_name");
            }
        }
        
        // 
        public string remark
        {
            get
            {
                return this.remarkValue;
            }
            set
            {
                this.remarkValue = value;
                this.OnPropertyChanged("remark");
            }
        }
        
        // 
        public string source
        {
            get
            {
                return this.sourceValue;
            }
            set
            {
                this.sourceValue = value;
                this.OnPropertyChanged("source");
            }
        }
        
        // 
        public string source_document
        {
            get
            {
                return this.source_documentValue;
            }
            set
            {
                this.source_documentValue = value;
                this.OnPropertyChanged("source_document");
            }
        }
        
        // 
        public string row_changed_by
        {
            get
            {
                return this.row_changed_byValue;
            }
            set
            {
                this.row_changed_byValue = value;
                this.OnPropertyChanged("row_changed_by");
            }
        }
        
        // 
        public System.DateTime row_changed_date
        {
            get
            {
                return this.row_changed_dateValue;
            }
            set
            {
                this.row_changed_dateValue = value;
                this.OnPropertyChanged("row_changed_date");
            }
        }
        
        // 
        public string row_created_by
        {
            get
            {
                return this.row_created_byValue;
            }
            set
            {
                this.row_created_byValue = value;
                this.OnPropertyChanged("row_created_by");
            }
        }
        
        // 
        public System.DateTime row_created_date
        {
            get
            {
                return this.row_created_dateValue;
            }
            set
            {
                this.row_created_dateValue = value;
                this.OnPropertyChanged("row_created_date");
            }
        }
        
        // 
        public string row_quality
        {
            get
            {
                return this.row_qualityValue;
            }
            set
            {
                this.row_qualityValue = value;
                this.OnPropertyChanged("row_quality");
            }
        }
        
        // 
        public string ClassName
        {
            get
            {
                return this.ClassNameValue;
            }
            set
            {
                this.ClassNameValue = value;
                this.OnPropertyChanged("ClassName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler;
            handler = this.PropertyChanged;
            if ((null != handler))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
