
using System.Collections.Generic;
using System.Text.RegularExpressions;
using TheTechIdea.Util;

namespace TheTechIdea.Beep.Helpers
{
    public static class RDBMSHelper
    {
        public static bool IsSqlStatementValid(string sqlString)
        {
            if (sqlString == null)
            {
                return false;
            }
            // List of SQL keywords
            string[] sqlKeywords = {
            "SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP",
            "FROM", "WHERE", "JOIN", "ON", "AND", "OR", "NOT", "IN", "LIKE"
            // Add more keywords as needed
        };

            // Create a regular expression pattern to match SQL keywords
            string pattern = @"\b(" + string.Join("|", sqlKeywords) + @")\b";

            // Use Regex to find matches
            MatchCollection matches = Regex.Matches(sqlString, pattern, RegexOptions.IgnoreCase);

            // If any keywords are found, return true
            return matches.Count > 0;
        }
        public static string GeneratePrimaryKeyQuery(DataSourceType rdbms, string tableName, string primaryKey, string type)
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} PRIMARY KEY IDENTITY;";
                    break;
                case DataSourceType.Mysql:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} PRIMARY KEY AUTO_INCREMENT;";
                    break;
                case DataSourceType.Postgre:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} PRIMARY KEY GENERATED ALWAYS AS IDENTITY;";
                    break;
                case DataSourceType.Oracle:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} GENERATED ALWAYS AS IDENTITY;";
                    break;
                case DataSourceType.DB2:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;";
                    break;
                case DataSourceType.FireBird:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} PRIMARY KEY;";
                    break;
                case DataSourceType.SqlLite:
                    query = $"ALTER TABLE {tableName} ADD {primaryKey} {type} PRIMARY KEY AUTOINCREMENT;";
                    break;
                case DataSourceType.Couchbase:
                case DataSourceType.Redis:
                case DataSourceType.MongoDB:
                    query = "NoSQL databases typically do not have primary keys in the same way RDBMS do.";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static string GenerateFetchNextSequenceValueQuery(DataSourceType rdbms, string sequenceName)
        {
            if (string.IsNullOrEmpty(sequenceName))
            {
                return "Sequence name must be provided.";
            }

            string query = "";

            switch (rdbms)
            {
                case DataSourceType.Oracle:
                    query = $"SELECT {sequenceName}.NEXTVAL FROM dual;";
                    break;
                case DataSourceType.Postgre:
                    query = $"SELECT nextval('{sequenceName}');";
                    break;
                case DataSourceType.SqlServer:
                    query = $"SELECT NEXT VALUE FOR {sequenceName};";
                    break;
                case DataSourceType.FireBird:
                    query = $"SELECT NEXT VALUE FOR {sequenceName} FROM RDB$DATABASE;";
                    break;
                case DataSourceType.DB2:
                    query = $"SELECT NEXTVAL FOR {sequenceName} FROM sysibm.sysdummy1;";
                    break;
                default:
                    query = "RDBMS not supported for sequences.";
                    break;
            }

            return query;
        }
        public static string GenerateFetchLastIdentityQuery(DataSourceType rdbms, string sequenceName = "")
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = "SELECT SCOPE_IDENTITY();";
                    break;
                case DataSourceType.Mysql:
                    query = "SELECT LAST_INSERT_ID();";
                    break;
                case DataSourceType.Postgre:
                    query = "SELECT LASTVAL();";
                    break;
                case DataSourceType.Oracle:
                    if (string.IsNullOrEmpty(sequenceName))
                    {
                        query = "Provide a sequence name.";
                    }
                    else
                    {
                        query = $"SELECT currval('{sequenceName}') FROM dual;";
                    }
                    break;
                case DataSourceType.FireBird:
                    if (string.IsNullOrEmpty(sequenceName))
                    {
                        query = "Provide a generator name.";
                    }
                    else
                    {
                        query = $"SELECT GEN_ID({sequenceName}, 0) FROM RDB$DATABASE;";
                    }
                    break;
                case DataSourceType.SqlLite:
                    query = "SELECT last_insert_rowid();";
                    break;
                case DataSourceType.DB2:
                    query = "SELECT IDENTITY_VAL_LOCAL() FROM sysibm.sysdummy1";
                    break;
                case DataSourceType.Cassandra:  // NOTE: Cassandra doesn't support this the same way relational DBs do
                    query = "Unsupported in Cassandra";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static string GenerateDropPrimaryKeyQuery(DataSourceType rdbms, string tableName, string constraintName)
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Mysql:
                    query = $"ALTER TABLE {tableName} DROP PRIMARY KEY;";
                    break;
                case DataSourceType.Postgre:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Oracle:
                    query = $"ALTER TABLE {tableName} DROP PRIMARY KEY;";
                    break;
                case DataSourceType.DB2:
                    query = $"ALTER TABLE {tableName} DROP PRIMARY KEY;";
                    break;
                case DataSourceType.FireBird:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.SqlLite:
                    query = "SQLite requires recreating the table to drop primary key.";
                    break;
                case DataSourceType.Couchbase:
                case DataSourceType.Redis:
                case DataSourceType.MongoDB:
                    query = "NoSQL databases typically do not have primary key constraints in the same way RDBMS do.";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static string GenerateDropForeignKeyQuery(DataSourceType rdbms, string tableName, string constraintName)
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Mysql:
                    query = $"ALTER TABLE {tableName} DROP FOREIGN KEY {constraintName};";
                    break;
                case DataSourceType.Postgre:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Oracle:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.DB2:
                    query = $"ALTER TABLE {tableName} DROP FOREIGN KEY {constraintName};";
                    break;
                case DataSourceType.FireBird:
                    query = $"ALTER TABLE {tableName} DROP CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.SqlLite:
                    query = "SQLite requires recreating the table to drop a foreign key.";
                    break;
                case DataSourceType.Couchbase:
                case DataSourceType.Redis:
                case DataSourceType.MongoDB:
                    query = "NoSQL databases typically do not have foreign key constraints in the same way RDBMS do.";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static string GenerateDisableForeignKeyQuery(DataSourceType rdbms, string tableName, string constraintName)
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = $"ALTER TABLE {tableName} NOCHECK CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Oracle:
                    query = $"ALTER TABLE {tableName} DISABLE CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Postgre:
                    query = $"ALTER TABLE {tableName} DISABLE TRIGGER ALL;";
                    break;
                case DataSourceType.Mysql:
                    query = "SET FOREIGN_KEY_CHECKS = 0;";
                    break;
                case DataSourceType.DB2:
                    query = $"ALTER TABLE {tableName} ALTER FOREIGN KEY {constraintName} NOT ENFORCED;";
                    break;
                case DataSourceType.FireBird:
                    query = $"ALTER TABLE {tableName} DISABLE TRIGGER {constraintName};";
                    break;
                case DataSourceType.SqlLite:
                    query = "PRAGMA foreign_keys = OFF;";
                    break;
                case DataSourceType.Couchbase:
                case DataSourceType.Redis:
                case DataSourceType.MongoDB:
                    query = "NoSQL databases typically do not have foreign key constraints in the same way RDBMS do.";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static string GenerateEnableForeignKeyQuery(DataSourceType rdbms, string tableName, string constraintName)
        {
            string query = "";

            switch (rdbms)
            {
                case DataSourceType.SqlServer:
                    query = $"ALTER TABLE {tableName} WITH CHECK CHECK CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Oracle:
                    query = $"ALTER TABLE {tableName} ENABLE CONSTRAINT {constraintName};";
                    break;
                case DataSourceType.Postgre:
                    // Assumes the constraint needs to be recreated
                    query = $"ALTER TABLE {tableName} ENABLE TRIGGER ALL;";
                    break;
                case DataSourceType.Mysql:
                    query = "SET FOREIGN_KEY_CHECKS = 1;";
                    break;
                case DataSourceType.DB2:
                    query = $"ALTER TABLE {tableName} ALTER FOREIGN KEY {constraintName} ENFORCED;";
                    break;
                case DataSourceType.FireBird:
                    query = $"ALTER TABLE {tableName} ENABLE TRIGGER {constraintName};";
                    break;
                case DataSourceType.SqlLite:
                    query = "PRAGMA foreign_keys = ON;";
                    break;
                case DataSourceType.Couchbase:
                case DataSourceType.Redis:
                case DataSourceType.MongoDB:
                    query = "NoSQL databases typically do not have foreign key constraints in the same way RDBMS do.";
                    break;
                default:
                    query = "RDBMS not supported.";
                    break;
            }

            return query;
        }
        public static List<QuerySqlRepo> CreateQuerySqlRepos()
        {
            return new List<QuerySqlRepo>
    {
        // Oracle
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT TABLE_NAME FROM user_tables", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT cols.column_name FROM all_constraints cons, all_cons_columns cols WHERE cols.table_name = '{0}' AND cons.constraint_type = 'P' AND cons.constraint_name = cols.constraint_name AND cons.owner = cols.owner", Sqlcommandtype.getPKforTable),
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT a.constraint_name, a.column_name, a.table_name FROM all_cons_columns a JOIN all_constraints c ON a.constraint_name = c.constraint_name WHERE c.constraint_type = 'R' AND a.table_name = '{0}'", Sqlcommandtype.getFKforTable),
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT table_name FROM all_constraints WHERE r_constraint_name IN (SELECT constraint_name FROM all_constraints WHERE table_name = '{0}' AND constraint_type = 'P')", Sqlcommandtype.getChildTable),
        new QuerySqlRepo(DataSourceType.Oracle, "SELECT r.table_name FROM all_constraints c JOIN all_constraints r ON c.r_constraint_name = r.constraint_name WHERE c.table_name = '{0}' AND c.constraint_type = 'R'", Sqlcommandtype.getParentTable),
        
        // SQL Server
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT t.NAME FROM sys.tables t INNER JOIN sys.schemas s ON t.schema_id = s.schema_id", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = '{0}' AND CONSTRAINT_NAME LIKE 'PK%'", Sqlcommandtype.getPKforTable),
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT FK.COLUMN_NAME, FK.TABLE_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE FK INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC ON FK.CONSTRAINT_NAME = TC.CONSTRAINT_NAME WHERE TC.CONSTRAINT_TYPE = 'FOREIGN KEY' AND FK.TABLE_NAME = '{0}'", Sqlcommandtype.getFKforTable),
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT FK.TABLE_NAME FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE FK ON RC.CONSTRAINT_NAME = FK.CONSTRAINT_NAME WHERE RC.UNIQUE_CONSTRAINT_NAME = (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = '{0}' AND CONSTRAINT_TYPE = 'PRIMARY KEY')", Sqlcommandtype.getChildTable),
        new QuerySqlRepo(DataSourceType.SqlServer, "SELECT RC.UNIQUE_CONSTRAINT_TABLE_NAME FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC WHERE RC.CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = '{0}')", Sqlcommandtype.getParentTable),
           // MySQL
        new QuerySqlRepo(DataSourceType.Mysql, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.Mysql, "SHOW TABLES", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.Mysql, "SHOW KEYS FROM {0} WHERE Key_name = 'PRIMARY'", Sqlcommandtype.getPKforTable),
        new QuerySqlRepo(DataSourceType.Mysql, "SELECT COLUMN_NAME AS child_column, REFERENCED_COLUMN_NAME AS parent_column, REFERENCED_TABLE_NAME AS parent_table FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'YourSchema' AND TABLE_NAME = '{0}' AND REFERENCED_TABLE_NAME IS NOT NULL", Sqlcommandtype.getFKforTable),
        new QuerySqlRepo(DataSourceType.Mysql, "SELECT TABLE_NAME AS child_table FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'YourSchema' AND REFERENCED_TABLE_NAME = '{0}'", Sqlcommandtype.getChildTable),
        new QuerySqlRepo(DataSourceType.Mysql, "SELECT REFERENCED_TABLE_NAME AS parent_table FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'YourSchema' AND TABLE_NAME = '{0}' AND REFERENCED_TABLE_NAME IS NOT NULL", Sqlcommandtype.getParentTable),

        // (Additional MySQL queries for FK, Child Table, Parent Table)

        // PostgreSQL
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT a.attname FROM pg_index i JOIN pg_attribute a ON a.attnum = ANY(i.indkey) WHERE i.indrelid = '{0}'::regclass AND i.indisprimary", Sqlcommandtype.getPKforTable),
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT conname AS constraint_name, a.attname AS child_column, af.attname AS parent_column, cl.relname AS parent_table FROM pg_attribute a JOIN pg_attribute af ON a.attnum = ANY(pg_constraint.confkey) JOIN pg_class cl ON pg_constraint.confrelid = cl.oid JOIN pg_constraint ON a.attnum = ANY(pg_constraint.conkey) WHERE a.attnum > 0 AND pg_constraint.conrelid = '{0}'::regclass", Sqlcommandtype.getFKforTable),
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT conname AS constraint_name, cl.relname AS child_table FROM pg_constraint JOIN pg_class cl ON pg_constraint.conrelid = cl.oid WHERE confrelid = '{0}'::regclass", Sqlcommandtype.getChildTable),
        new QuerySqlRepo(DataSourceType.Postgre, "SELECT confrelid::regclass AS parent_table FROM pg_constraint WHERE conrelid = '{0}'::regclass", Sqlcommandtype.getParentTable),


        // SQLite
        new QuerySqlRepo(DataSourceType.SqlLite, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.SqlLite, "SELECT name table_name FROM sqlite_master WHERE type='table'", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.SqlLite, "PRAGMA table_info({0})", Sqlcommandtype.getPKforTable),
        // (Additional SQLite queries for FK, Child Table, Parent Table)

       // DB2
        new QuerySqlRepo(DataSourceType.DB2, "SELECT * FROM {0} {2}", Sqlcommandtype.getTable),
        new QuerySqlRepo(DataSourceType.DB2, "SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = CURRENT SCHEMA", Sqlcommandtype.getlistoftables),
        new QuerySqlRepo(DataSourceType.DB2, "SELECT COLNAME COLUMN_NAME FROM SYSCAT.KEYCOLUSE WHERE TABNAME = '{0}' AND CONSTRAINTNAME LIKE 'PK%'", Sqlcommandtype.getPKforTable),
        new QuerySqlRepo(DataSourceType.DB2, "SELECT FK_COLNAMES AS child_column, PK_COLNAMES AS parent_column, PK_TBNAME AS parent_table FROM SYSIBM.SQLFOREIGNKEYS WHERE FK_TBNAME = '{0}'", Sqlcommandtype.getFKforTable),
        new QuerySqlRepo(DataSourceType.DB2, "SELECT FK_TBNAME AS child_table FROM SYSIBM.SQLFOREIGNKEYS WHERE PK_TBNAME = '{0}'", Sqlcommandtype.getChildTable),
        new QuerySqlRepo(DataSourceType.DB2, "SELECT PK_TBNAME AS parent_table FROM SYSIBM.SQLFOREIGNKEYS WHERE FK_TBNAME = '{0}'", Sqlcommandtype.getParentTable),
     // (Additional DB2 queries for FK, Child Table, Parent Table)
        // ... (You can add similar entries for MySQL, PostgreSQL, SQLite, and DB2)
    };
        }
    }
}
